### ISSUE TITLE
???????????????????????

### ISSUE THREAD

**Issue by wowjeeez** [fjuton/nui_devblock#2]
Why would u ever make a script like this lmao

**Comment by wowjeeez** [comment]
also its very easy to bypass

**Comment by fjuton** [comment]
This script is done for people that can't do simple checks in server side because they are too dumb for scripting. Why? Because people started using Javascript execution through nui_devtools

**Comment by fjuton** [comment]
And probably not going to update this anymore

**Comment by wowjeeez** [comment]
> And probably not going to update this anymore

good

>  they are too dumb for scripting

Make learning resources then and solve the problem at it's root
